/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tekniti.skilltransit.service.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.tekniti.skilltransit.service.model.SkillSubCategory;
import com.tekniti.skilltransit.service.model.SkillSubCategoryModel;
import com.tekniti.skilltransit.service.model.SkillSubCategorySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SkillSubCategory service. Represents a row in the &quot;skill_subcategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.tekniti.skilltransit.service.model.SkillSubCategoryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SkillSubCategoryImpl}.
 * </p>
 *
 * @author Hari
 * @see SkillSubCategoryImpl
 * @see com.tekniti.skilltransit.service.model.SkillSubCategory
 * @see com.tekniti.skilltransit.service.model.SkillSubCategoryModel
 * @generated
 */
@JSON(strict = true)
public class SkillSubCategoryModelImpl extends BaseModelImpl<SkillSubCategory>
	implements SkillSubCategoryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a skill sub category model instance should use the {@link com.tekniti.skilltransit.service.model.SkillSubCategory} interface instead.
	 */
	public static final String TABLE_NAME = "skill_subcategory";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table skill_subcategory (id LONG not null primary key,name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table skill_subcategory";
	public static final String ORDER_BY_JPQL = " ORDER BY skillSubCategory.primaryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY skill_subcategory.id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.tekniti.skilltransit.service.model.SkillSubCategory"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.tekniti.skilltransit.service.model.SkillSubCategory"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SkillSubCategory toModel(SkillSubCategorySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SkillSubCategory model = new SkillSubCategoryImpl();

		model.setPrimaryId(soapModel.getPrimaryId());
		model.setName(soapModel.getName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SkillSubCategory> toModels(
		SkillSubCategorySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SkillSubCategory> models = new ArrayList<SkillSubCategory>(soapModels.length);

		for (SkillSubCategorySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.tekniti.skilltransit.service.model.SkillSubCategory"));

	public SkillSubCategoryModelImpl() {
	}

	public long getPrimaryKey() {
		return _primaryId;
	}

	public void setPrimaryKey(long primaryKey) {
		setPrimaryId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_primaryId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return SkillSubCategory.class;
	}

	public String getModelClassName() {
		return SkillSubCategory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("primaryId", getPrimaryId());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long primaryId = (Long)attributes.get("primaryId");

		if (primaryId != null) {
			setPrimaryId(primaryId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	@JSON
	public long getPrimaryId() {
		return _primaryId;
	}

	public void setPrimaryId(long primaryId) {
		_primaryId = primaryId;
	}

	@JSON
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SkillSubCategory.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SkillSubCategory toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SkillSubCategory)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public SkillSubCategory toUnescapedModel() {
		return (SkillSubCategory)this;
	}

	@Override
	public Object clone() {
		SkillSubCategoryImpl skillSubCategoryImpl = new SkillSubCategoryImpl();

		skillSubCategoryImpl.setPrimaryId(getPrimaryId());
		skillSubCategoryImpl.setName(getName());

		skillSubCategoryImpl.resetOriginalValues();

		return skillSubCategoryImpl;
	}

	public int compareTo(SkillSubCategory skillSubCategory) {
		int value = 0;

		if (getPrimaryId() < skillSubCategory.getPrimaryId()) {
			value = -1;
		}
		else if (getPrimaryId() > skillSubCategory.getPrimaryId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SkillSubCategory)) {
			return false;
		}

		SkillSubCategory skillSubCategory = (SkillSubCategory)obj;

		long primaryKey = skillSubCategory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<SkillSubCategory> toCacheModel() {
		SkillSubCategoryCacheModel skillSubCategoryCacheModel = new SkillSubCategoryCacheModel();

		skillSubCategoryCacheModel.primaryId = getPrimaryId();

		skillSubCategoryCacheModel.name = getName();

		String name = skillSubCategoryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			skillSubCategoryCacheModel.name = null;
		}

		return skillSubCategoryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{primaryId=");
		sb.append(getPrimaryId());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.tekniti.skilltransit.service.model.SkillSubCategory");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>primaryId</column-name><column-value><![CDATA[");
		sb.append(getPrimaryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SkillSubCategory.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SkillSubCategory.class
		};
	private long _primaryId;
	private String _name;
	private SkillSubCategory _escapedModel;
}