/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tekniti.skilltransit.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UserDetails service. Represents a row in the &quot;user_details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tekniti.skilltransit.service.model.impl.UserDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tekniti.skilltransit.service.model.impl.UserDetailsImpl}.
 * </p>
 *
 * @author Hari
 * @see UserDetails
 * @see com.tekniti.skilltransit.service.model.impl.UserDetailsImpl
 * @see com.tekniti.skilltransit.service.model.impl.UserDetailsModelImpl
 * @generated
 */
public interface UserDetailsModel extends BaseModel<UserDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user details model instance should use the {@link UserDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this user details.
	 *
	 * @return the primary key of this user details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user details.
	 *
	 * @param primaryKey the primary key of this user details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this user details.
	 *
	 * @return the user ID of this user details
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user details.
	 *
	 * @param userId the user ID of this user details
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user details.
	 *
	 * @return the user uuid of this user details
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user details.
	 *
	 * @param userUuid the user uuid of this user details
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the hourly rate of this user details.
	 *
	 * @return the hourly rate of this user details
	 */
	@AutoEscape
	public String getHourlyRate();

	/**
	 * Sets the hourly rate of this user details.
	 *
	 * @param hourlyRate the hourly rate of this user details
	 */
	public void setHourlyRate(String hourlyRate);

	/**
	 * Returns the zip code of this user details.
	 *
	 * @return the zip code of this user details
	 */
	@AutoEscape
	public String getZipCode();

	/**
	 * Sets the zip code of this user details.
	 *
	 * @param zipCode the zip code of this user details
	 */
	public void setZipCode(String zipCode);

	/**
	 * Returns the category of this user details.
	 *
	 * @return the category of this user details
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this user details.
	 *
	 * @param category the category of this user details
	 */
	public void setCategory(String category);

	/**
	 * Returns the client of this user details.
	 *
	 * @return the client of this user details
	 */
	@AutoEscape
	public String getClient();

	/**
	 * Sets the client of this user details.
	 *
	 * @param client the client of this user details
	 */
	public void setClient(String client);

	/**
	 * Returns the commute of this user details.
	 *
	 * @return the commute of this user details
	 */
	@AutoEscape
	public String getCommute();

	/**
	 * Sets the commute of this user details.
	 *
	 * @param commute the commute of this user details
	 */
	public void setCommute(String commute);

	/**
	 * Returns the skill of this user details.
	 *
	 * @return the skill of this user details
	 */
	@AutoEscape
	public String getSkill();

	/**
	 * Sets the skill of this user details.
	 *
	 * @param skill the skill of this user details
	 */
	public void setSkill(String skill);

	/**
	 * Returns the state of this user details.
	 *
	 * @return the state of this user details
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this user details.
	 *
	 * @param state the state of this user details
	 */
	public void setState(String state);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(UserDetails userDetails);

	public int hashCode();

	public CacheModel<UserDetails> toCacheModel();

	public UserDetails toEscapedModel();

	public UserDetails toUnescapedModel();

	public String toString();

	public String toXmlString();
}