/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tekniti.skilltransit.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UserSkills service. Represents a row in the &quot;user_skills&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tekniti.skilltransit.service.model.impl.UserSkillsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tekniti.skilltransit.service.model.impl.UserSkillsImpl}.
 * </p>
 *
 * @author Hari
 * @see UserSkills
 * @see com.tekniti.skilltransit.service.model.impl.UserSkillsImpl
 * @see com.tekniti.skilltransit.service.model.impl.UserSkillsModelImpl
 * @generated
 */
public interface UserSkillsModel extends BaseModel<UserSkills> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user skills model instance should use the {@link UserSkills} interface instead.
	 */

	/**
	 * Returns the primary key of this user skills.
	 *
	 * @return the primary key of this user skills
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user skills.
	 *
	 * @param primaryKey the primary key of this user skills
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the prim ID of this user skills.
	 *
	 * @return the prim ID of this user skills
	 */
	public long getPrimId();

	/**
	 * Sets the prim ID of this user skills.
	 *
	 * @param primId the prim ID of this user skills
	 */
	public void setPrimId(long primId);

	/**
	 * Returns the name of this user skills.
	 *
	 * @return the name of this user skills
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this user skills.
	 *
	 * @param name the name of this user skills
	 */
	public void setName(String name);

	/**
	 * Returns the user_id of this user skills.
	 *
	 * @return the user_id of this user skills
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this user skills.
	 *
	 * @param user_id the user_id of this user skills
	 */
	public void setUser_id(long user_id);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(UserSkills userSkills);

	public int hashCode();

	public CacheModel<UserSkills> toCacheModel();

	public UserSkills toEscapedModel();

	public UserSkills toUnescapedModel();

	public String toString();

	public String toXmlString();
}